
USE CONSTRUCT;

SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS BUSINESS_DEFINE;
DROP TABLE IF EXISTS BUSINESS_FILE_DEFINE;

CREATE TABLE BUSINESS_DEFINE
(
    NAME varchar(32) NOT NULL,
    ID varchar(32) NOT NULL,
    PROCESS varchar(32),
    DESCRIPTION_TEMPLATE text NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE BUSINESS_FILE_DEFINE
(
    BUSINESS varchar(32) NOT NULL,
    _ORDER int NOT NULL,
    NAME varchar(512) NOT NULL,
    TYPE varchar(4) NOT NULL,
    EL varchar(512) NULL,
    DESCRIPTION varchar(1024),
    PRIMARY KEY (BUSINESS, _ORDER)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */



ALTER TABLE BUSINESS_FILE_DEFINE
    ADD FOREIGN KEY (BUSINESS)
        REFERENCES BUSINESS_DEFINE (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

SET SESSION FOREIGN_KEY_CHECKS=1;